### ISSUE TITLE
Set url for strava after registration not possible

### ISSUE THREAD

**Issue by whitesheep80** [MatthiasHeilManchester/rvy_racing#67]
for me it was not possible to set the url for the strava athlete page. maybe it is missing or unable to fine. so please fix that.

**Comment by MatthiasHeilManchester** [comment]
Well hidden, but it's there: Main website for rvy_racing -> Board index ->  User Control Panel ->  Profile -> Edit profile

Will add an item to the FAQ.

**Comment by whitesheep80** [comment]
thx a lot....🙏

Am Fr., 2. Sept. 2022 um 18:50 Uhr schrieb MatthiasHeilManchester <
***@***.***>:

**Comment by whitesheep80** [comment]
sry just checked that out to recognise that there is no edit profile....sry
(screen attached)
[image: grafik.png]


Am Fr., 2. Sept. 2022 um 18:47 Uhr schrieb MatthiasHeilManchester <
***@***.***>:
